//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 03:17:20 PM COT 
//


package com.growupit.gideesquema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.growupit.gideesquema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArchivoElectronico_QNAME = new QName("http://www.growupit.com/gideEsquema", "ArchivoElectronico");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.growupit.gideesquema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TipoExternalReference }
     * 
     */
    public TipoExternalReference createTipoExternalReference() {
        return new TipoExternalReference();
    }

    /**
     * Create an instance of {@link TipoProveedor }
     * 
     */
    public TipoProveedor createTipoProveedor() {
        return new TipoProveedor();
    }

    /**
     * Create an instance of {@link TipoRegimenTriburario }
     * 
     */
    public TipoRegimenTriburario createTipoRegimenTriburario() {
        return new TipoRegimenTriburario();
    }

    /**
     * Create an instance of {@link TipoTexto }
     * 
     */
    public TipoTexto createTipoTexto() {
        return new TipoTexto();
    }

    /**
     * Create an instance of {@link TipoPago }
     * 
     */
    public TipoPago createTipoPago() {
        return new TipoPago();
    }

    /**
     * Create an instance of {@link TipoPrecio }
     * 
     */
    public TipoPrecio createTipoPrecio() {
        return new TipoPrecio();
    }

    /**
     * Create an instance of {@link TipoReferenciaLineaFactura }
     * 
     */
    public TipoReferenciaLineaFactura createTipoReferenciaLineaFactura() {
        return new TipoReferenciaLineaFactura();
    }

    /**
     * Create an instance of {@link TipoIdentificacionArticulos }
     * 
     */
    public TipoIdentificacionArticulos createTipoIdentificacionArticulos() {
        return new TipoIdentificacionArticulos();
    }

    /**
     * Create an instance of {@link TipoContenidoExtension }
     * 
     */
    public TipoContenidoExtension createTipoContenidoExtension() {
        return new TipoContenidoExtension();
    }

    /**
     * Create an instance of {@link TipoArticulo }
     * 
     */
    public TipoArticulo createTipoArticulo() {
        return new TipoArticulo();
    }

    /**
     * Create an instance of {@link TipoContrato }
     * 
     */
    public TipoContrato createTipoContrato() {
        return new TipoContrato();
    }

    /**
     * Create an instance of {@link TipoReferenciaPedido }
     * 
     */
    public TipoReferenciaPedido createTipoReferenciaPedido() {
        return new TipoReferenciaPedido();
    }

    /**
     * Create an instance of {@link TipoTemperatura }
     * 
     */
    public TipoTemperatura createTipoTemperatura() {
        return new TipoTemperatura();
    }

    /**
     * Create an instance of {@link TipoCondicionesTransaccion }
     * 
     */
    public TipoCondicionesTransaccion createTipoCondicionesTransaccion() {
        return new TipoCondicionesTransaccion();
    }

    /**
     * Create an instance of {@link TipoExtensiones }
     * 
     */
    public TipoExtensiones createTipoExtensiones() {
        return new TipoExtensiones();
    }

    /**
     * Create an instance of {@link TipoIdentificador }
     * 
     */
    public TipoIdentificador createTipoIdentificador() {
        return new TipoIdentificador();
    }

    /**
     * Create an instance of {@link TipoPropiedadArticulo }
     * 
     */
    public TipoPropiedadArticulo createTipoPropiedadArticulo() {
        return new TipoPropiedadArticulo();
    }

    /**
     * Create an instance of {@link TipoTerminosPago }
     * 
     */
    public TipoTerminosPago createTipoTerminosPago() {
        return new TipoTerminosPago();
    }

    /**
     * Create an instance of {@link TipoListaPrecios }
     * 
     */
    public TipoListaPrecios createTipoListaPrecios() {
        return new TipoListaPrecios();
    }

    /**
     * Create an instance of {@link TipoDetalleFactura }
     * 
     */
    public TipoDetalleFactura createTipoDetalleFactura() {
        return new TipoDetalleFactura();
    }

    /**
     * Create an instance of {@link TipoReferenciaFactura }
     * 
     */
    public TipoReferenciaFactura createTipoReferenciaFactura() {
        return new TipoReferenciaFactura();
    }

    /**
     * Create an instance of {@link TipoEntrega }
     * 
     */
    public TipoEntrega createTipoEntrega() {
        return new TipoEntrega();
    }

    /**
     * Create an instance of {@link ArchivoElectronicoTipo }
     * 
     */
    public ArchivoElectronicoTipo createArchivoElectronicoTipo() {
        return new ArchivoElectronicoTipo();
    }

    /**
     * Create an instance of {@link TipoGrupoPropiedadesArticulo }
     * 
     */
    public TipoGrupoPropiedadesArticulo createTipoGrupoPropiedadesArticulo() {
        return new TipoGrupoPropiedadesArticulo();
    }

    /**
     * Create an instance of {@link TipoTerminosEntrega }
     * 
     */
    public TipoTerminosEntrega createTipoTerminosEntrega() {
        return new TipoTerminosEntrega();
    }

    /**
     * Create an instance of {@link TipoDatosDeControl }
     * 
     */
    public TipoDatosDeControl createTipoDatosDeControl() {
        return new TipoDatosDeControl();
    }

    /**
     * Create an instance of {@link TipoSucursal }
     * 
     */
    public TipoSucursal createTipoSucursal() {
        return new TipoSucursal();
    }

    /**
     * Create an instance of {@link TipoCargo }
     * 
     */
    public TipoCargo createTipoCargo() {
        return new TipoCargo();
    }

    /**
     * Create an instance of {@link TipoDireccion }
     * 
     */
    public TipoDireccion createTipoDireccion() {
        return new TipoDireccion();
    }

    /**
     * Create an instance of {@link TipoSubtotalImpuesto }
     * 
     */
    public TipoSubtotalImpuesto createTipoSubtotalImpuesto() {
        return new TipoSubtotalImpuesto();
    }

    /**
     * Create an instance of {@link TipoInstanciaArticulo }
     * 
     */
    public TipoInstanciaArticulo createTipoInstanciaArticulo() {
        return new TipoInstanciaArticulo();
    }

    /**
     * Create an instance of {@link TipoUbicacion }
     * 
     */
    public TipoUbicacion createTipoUbicacion() {
        return new TipoUbicacion();
    }

    /**
     * Create an instance of {@link TipoComunicacion }
     * 
     */
    public TipoComunicacion createTipoComunicacion() {
        return new TipoComunicacion();
    }

    /**
     * Create an instance of {@link TipoUnidadEntrega }
     * 
     */
    public TipoUnidadEntrega createTipoUnidadEntrega() {
        return new TipoUnidadEntrega();
    }

    /**
     * Create an instance of {@link TipoExtension }
     * 
     */
    public TipoExtension createTipoExtension() {
        return new TipoExtension();
    }

    /**
     * Create an instance of {@link TipoContacto }
     * 
     */
    public TipoContacto createTipoContacto() {
        return new TipoContacto();
    }

    /**
     * Create an instance of {@link TipoPeriodo }
     * 
     */
    public TipoPeriodo createTipoPeriodo() {
        return new TipoPeriodo();
    }

    /**
     * Create an instance of {@link TipoCuentaTarjeta }
     * 
     */
    public TipoCuentaTarjeta createTipoCuentaTarjeta() {
        return new TipoCuentaTarjeta();
    }

    /**
     * Create an instance of {@link TipoImpuestoCategoria }
     * 
     */
    public TipoImpuestoCategoria createTipoImpuestoCategoria() {
        return new TipoImpuestoCategoria();
    }

    /**
     * Create an instance of {@link TipoReferenciaPrecios }
     * 
     */
    public TipoReferenciaPrecios createTipoReferenciaPrecios() {
        return new TipoReferenciaPrecios();
    }

    /**
     * Create an instance of {@link TipoDimension }
     * 
     */
    public TipoDimension createTipoDimension() {
        return new TipoDimension();
    }

    /**
     * Create an instance of {@link TipoEsquemaImpuestosTercero }
     * 
     */
    public TipoEsquemaImpuestosTercero createTipoEsquemaImpuestosTercero() {
        return new TipoEsquemaImpuestosTercero();
    }

    /**
     * Create an instance of {@link TipoObjetoBinario }
     * 
     */
    public TipoObjetoBinario createTipoObjetoBinario() {
        return new TipoObjetoBinario();
    }

    /**
     * Create an instance of {@link TipoClienteTercero }
     * 
     */
    public TipoClienteTercero createTipoClienteTercero() {
        return new TipoClienteTercero();
    }

    /**
     * Create an instance of {@link TipoTransitoBienArriesgado }
     * 
     */
    public TipoTransitoBienArriesgado createTipoTransitoBienArriesgado() {
        return new TipoTransitoBienArriesgado();
    }

    /**
     * Create an instance of {@link TipoEnvio }
     * 
     */
    public TipoEnvio createTipoEnvio() {
        return new TipoEnvio();
    }

    /**
     * Create an instance of {@link TipoLineaReferencia }
     * 
     */
    public TipoLineaReferencia createTipoLineaReferencia() {
        return new TipoLineaReferencia();
    }

    /**
     * Create an instance of {@link TipoImpuestoTotal }
     * 
     */
    public TipoImpuestoTotal createTipoImpuestoTotal() {
        return new TipoImpuestoTotal();
    }

    /**
     * Create an instance of {@link TipoIdentificacionLote }
     * 
     */
    public TipoIdentificacionLote createTipoIdentificacionLote() {
        return new TipoIdentificacionLote();
    }

    /**
     * Create an instance of {@link TipoPersona }
     * 
     */
    public TipoPersona createTipoPersona() {
        return new TipoPersona();
    }

    /**
     * Create an instance of {@link TipoRiesgoSecundario }
     * 
     */
    public TipoRiesgoSecundario createTipoRiesgoSecundario() {
        return new TipoRiesgoSecundario();
    }

    /**
     * Create an instance of {@link TipoClasificacionMercancia }
     * 
     */
    public TipoClasificacionMercancia createTipoClasificacionMercancia() {
        return new TipoClasificacionMercancia();
    }

    /**
     * Create an instance of {@link TipoPais }
     * 
     */
    public TipoPais createTipoPais() {
        return new TipoPais();
    }

    /**
     * Create an instance of {@link TipoEsquemaRegistroCorporativo }
     * 
     */
    public TipoEsquemaRegistroCorporativo createTipoEsquemaRegistroCorporativo() {
        return new TipoEsquemaRegistroCorporativo();
    }

    /**
     * Create an instance of {@link TipoCoordenadasUbicacion }
     * 
     */
    public TipoCoordenadasUbicacion createTipoCoordenadasUbicacion() {
        return new TipoCoordenadasUbicacion();
    }

    /**
     * Create an instance of {@link TipoArticuloPeligroso }
     * 
     */
    public TipoArticuloPeligroso createTipoArticuloPeligroso() {
        return new TipoArticuloPeligroso();
    }

    /**
     * Create an instance of {@link TipoTercero }
     * 
     */
    public TipoTercero createTipoTercero() {
        return new TipoTercero();
    }

    /**
     * Create an instance of {@link TipoInstitucionFinanciera }
     * 
     */
    public TipoInstitucionFinanciera createTipoInstitucionFinanciera() {
        return new TipoInstitucionFinanciera();
    }

    /**
     * Create an instance of {@link TipoUbicacionCantidadArticulo }
     * 
     */
    public TipoUbicacionCantidadArticulo createTipoUbicacionCantidadArticulo() {
        return new TipoUbicacionCantidadArticulo();
    }

    /**
     * Create an instance of {@link TipoAtriburoFisico }
     * 
     */
    public TipoAtriburoFisico createTipoAtriburoFisico() {
        return new TipoAtriburoFisico();
    }

    /**
     * Create an instance of {@link TipoCodigo }
     * 
     */
    public TipoCodigo createTipoCodigo() {
        return new TipoCodigo();
    }

    /**
     * Create an instance of {@link TipoArchivoAdjunto }
     * 
     */
    public TipoArchivoAdjunto createTipoArchivoAdjunto() {
        return new TipoArchivoAdjunto();
    }

    /**
     * Create an instance of {@link TipoMedioPago }
     * 
     */
    public TipoMedioPago createTipoMedioPago() {
        return new TipoMedioPago();
    }

    /**
     * Create an instance of {@link TipoTasaCambio }
     * 
     */
    public TipoTasaCambio createTipoTasaCambio() {
        return new TipoTasaCambio();
    }

    /**
     * Create an instance of {@link TipoIdioma }
     * 
     */
    public TipoIdioma createTipoIdioma() {
        return new TipoIdioma();
    }

    /**
     * Create an instance of {@link TipoDocumentoReferencia }
     * 
     */
    public TipoDocumentoReferencia createTipoDocumentoReferencia() {
        return new TipoDocumentoReferencia();
    }

    /**
     * Create an instance of {@link TipoEntidadLegalTercero }
     * 
     */
    public TipoEntidadLegalTercero createTipoEntidadLegalTercero() {
        return new TipoEntidadLegalTercero();
    }

    /**
     * Create an instance of {@link TipoCuentaFinanciera }
     * 
     */
    public TipoCuentaFinanciera createTipoCuentaFinanciera() {
        return new TipoCuentaFinanciera();
    }

    /**
     * Create an instance of {@link TipoTotalMonetarioLegal }
     * 
     */
    public TipoTotalMonetarioLegal createTipoTotalMonetarioLegal() {
        return new TipoTotalMonetarioLegal();
    }

    /**
     * Create an instance of {@link TipoReferenciaLineaPedido }
     * 
     */
    public TipoReferenciaLineaPedido createTipoReferenciaLineaPedido() {
        return new TipoReferenciaLineaPedido();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchivoElectronicoTipo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.growupit.com/gideEsquema", name = "ArchivoElectronico")
    public JAXBElement<ArchivoElectronicoTipo> createArchivoElectronico(ArchivoElectronicoTipo value) {
        return new JAXBElement<ArchivoElectronicoTipo>(_ArchivoElectronico_QNAME, ArchivoElectronicoTipo.class, null, value);
    }

}
