
package co.clientes.services.establecimientoseducativos;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServicioEstablecimientoEducativo", targetNamespace = "http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServicioEstablecimientoEducativo {


    /**
     * 
     * @param filtroEstablecimientosEducativos
     * @return
     *     returns co.clientes.services.EstablecimientosEducativosPaginado
     */
    @WebMethod(action = "http://www.mineducacion.gov.co/ServiciosSineb/obtenerEstablecimientosEducativos")
    @WebResult(name = "establecimientosEducativosPaginado", targetNamespace = "")
    @RequestWrapper(localName = "obtenerEstablecimientosEducativos", targetNamespace = "http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", className = "co.clientes.services.ObtenerEstablecimientosEducativos")
    @ResponseWrapper(localName = "obtenerEstablecimientosEducativosResponse", targetNamespace = "http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", className = "co.clientes.services.ObtenerEstablecimientosEducativosResponse")
    @Action(input = "http://www.mineducacion.gov.co/ServiciosSineb/obtenerEstablecimientosEducativos", output = "http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/IServicioEstablecimientoEducativo/obtenerEstablecimientosEducativosResponse")
    public EstablecimientosEducativosPaginado obtenerEstablecimientosEducativos(
        @WebParam(name = "filtroEstablecimientosEducativos", targetNamespace = "")
        FiltroEstablecimientosEducativos filtroEstablecimientosEducativos);

    /**
     * 
     * @param codDaneEstablecimientoEducativo
     * @return
     *     returns co.clientes.services.EstablecimientoEducativo
     */
    @WebMethod(action = "http://www.mineducacion.gov.co/ServiciosSineb/obtenerEstablecimientoEducativo")
    @WebResult(name = "establecimientoEducativo", targetNamespace = "")
    @RequestWrapper(localName = "obtenerEstablecimientoEducativo", targetNamespace = "http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", className = "co.clientes.services.ObtenerEstablecimientoEducativo")
    @ResponseWrapper(localName = "obtenerEstablecimientoEducativoResponse", targetNamespace = "http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", className = "co.clientes.services.ObtenerEstablecimientoEducativoResponse")
    @Action(input = "http://www.mineducacion.gov.co/ServiciosSineb/obtenerEstablecimientoEducativo", output = "http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/IServicioEstablecimientoEducativo/obtenerEstablecimientoEducativoResponse")
    public EstablecimientoEducativo obtenerEstablecimientoEducativo(
        @WebParam(name = "codDaneEstablecimientoEducativo", targetNamespace = "")
        String codDaneEstablecimientoEducativo);

}
