
package co.clientes.services.establecimientoseducativos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioEstablecimientoEducativoService", targetNamespace = "http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", wsdlLocation = "file:/D:/EstablecimientoEducativo/EstablecimientoEducativo_1.wsdl")
public class ServicioEstablecimientoEducativoService
    extends Service
{

    private final static URL SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_EXCEPTION;
    private final static QName SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_QNAME = new QName("http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", "ServicioEstablecimientoEducativoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/EstablecimientoEducativo/EstablecimientoEducativo_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_WSDL_LOCATION = url;
        SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_EXCEPTION = e;
    }

    public ServicioEstablecimientoEducativoService() {
        super(__getWsdlLocation(), SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_QNAME);
    }

    public ServicioEstablecimientoEducativoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_QNAME, features);
    }

    public ServicioEstablecimientoEducativoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_QNAME);
    }

    public ServicioEstablecimientoEducativoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_QNAME, features);
    }

    public ServicioEstablecimientoEducativoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioEstablecimientoEducativoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServicioEstablecimientoEducativo
     */
    @WebEndpoint(name = "IServicioEstablecimientoEducativoPort")
    public IServicioEstablecimientoEducativo getIServicioEstablecimientoEducativoPort() {
        return super.getPort(new QName("http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", "IServicioEstablecimientoEducativoPort"), IServicioEstablecimientoEducativo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServicioEstablecimientoEducativo
     */
    @WebEndpoint(name = "IServicioEstablecimientoEducativoPort")
    public IServicioEstablecimientoEducativo getIServicioEstablecimientoEducativoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", "IServicioEstablecimientoEducativoPort"), IServicioEstablecimientoEducativo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_EXCEPTION!= null) {
            throw SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_EXCEPTION;
        }
        return SERVICIOESTABLECIMIENTOEDUCATIVOSERVICE_WSDL_LOCATION;
    }

}
