
package co.clientes.services.sedeseducativas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioSedeEducativaService", targetNamespace = "http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", wsdlLocation = "file:/D:/EstablecimientoEducativo/SedeEducativa_1.wsdl")
public class ServicioSedeEducativaService
    extends Service
{

    private final static URL SERVICIOSEDEEDUCATIVASERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOSEDEEDUCATIVASERVICE_EXCEPTION;
    private final static QName SERVICIOSEDEEDUCATIVASERVICE_QNAME = new QName("http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", "ServicioSedeEducativaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/EstablecimientoEducativo/SedeEducativa_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOSEDEEDUCATIVASERVICE_WSDL_LOCATION = url;
        SERVICIOSEDEEDUCATIVASERVICE_EXCEPTION = e;
    }

    public ServicioSedeEducativaService() {
        super(__getWsdlLocation(), SERVICIOSEDEEDUCATIVASERVICE_QNAME);
    }

    public ServicioSedeEducativaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOSEDEEDUCATIVASERVICE_QNAME, features);
    }

    public ServicioSedeEducativaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOSEDEEDUCATIVASERVICE_QNAME);
    }

    public ServicioSedeEducativaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOSEDEEDUCATIVASERVICE_QNAME, features);
    }

    public ServicioSedeEducativaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioSedeEducativaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServicioSedeEducativa
     */
    @WebEndpoint(name = "IServicioSedeEducativaPort")
    public IServicioSedeEducativa getIServicioSedeEducativaPort() {
        return super.getPort(new QName("http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", "IServicioSedeEducativaPort"), IServicioSedeEducativa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServicioSedeEducativa
     */
    @WebEndpoint(name = "IServicioSedeEducativaPort")
    public IServicioSedeEducativa getIServicioSedeEducativaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/", "IServicioSedeEducativaPort"), IServicioSedeEducativa.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOSEDEEDUCATIVASERVICE_EXCEPTION!= null) {
            throw SERVICIOSEDEEDUCATIVASERVICE_EXCEPTION;
        }
        return SERVICIOSEDEEDUCATIVASERVICE_WSDL_LOCATION;
    }

}
