//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 09:18:26 AM CEST 
//


package co.gide.traslate.firma;

import java.security.cert.X509CRL;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidateCertType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidateCertType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CRLPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://data.signature.mmdd.indra.com}ValidateCertTypeImpl"/>
 *         &lt;element name="validateCertCache" type="{http://data.signature.mmdd.indra.com}ValidateCertCacheType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidateCertType", propOrder = {
    "crls",
    "type",
    "validateCertCache"
})

public class ValidateCertType {

    @XmlElement(name = "crls", required = true)
    protected List<X509CRL> crls;
    @XmlElement(required = true)
    protected ValidateCertTypeImpl type;
    protected List<ValidateCertCacheType> validateCertCache;

    /**
     * Gets the value of the crls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link X509CRL }
     * 
     * 
     */
    public List<X509CRL> getCrls() {
        if (crls == null) {
            crls = new ArrayList<X509CRL>();
        }
        return this.crls;
    }

   
    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ValidateCertTypeImpl }
     *     
     */
    public ValidateCertTypeImpl getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidateCertTypeImpl }
     *     
     */
    public void setType(ValidateCertTypeImpl value) {
        this.type = value;
    }

    /**
     * Gets the value of the validateCertCache property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validateCertCache property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidateCertCache().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValidateCertCacheType }
     * 
     * 
     */
    public List<ValidateCertCacheType> getValidateCertCache() {
        if (validateCertCache == null) {
            validateCertCache = new ArrayList<ValidateCertCacheType>();
        }
        return this.validateCertCache;
    }

}
