//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 09:18:26 AM CEST 
//


package co.gide.traslate.firma;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for ValidateCertTypeImpl.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ValidateCertTypeImpl">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CRLSTANDARD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ValidateCertTypeImpl")
@XmlEnum

public enum ValidateCertTypeImpl {

    CRLSTANDARD;

    public String value() {
        return name();
    }

    public static ValidateCertTypeImpl fromValue(String v) {
        return valueOf(v);
    }

}
